d = int(input("날짜:"))
c = [0,0,0,0,0]

c[0]=int(input("첫번째 자동차의 끝번호:"))
c[1]=int(input("두번째 자동차의 끝번호:"))
c[2]=int(input("세번째 자동차의 끝번호:"))
c[3]=int(input("네번째 자동차의 끝번호:"))
c[4]=int(input("다섯번째 자동차의 끝번호:"))
c[0]=int(input("첫번째 자동차의 끝번호:"))
c[1]=int(input("두번째 자동차의 끝번호:"))
c[2]=int(input("세번째 자동차의 끝번호:"))
c[3]=int(input("네번째 자동차의 끝번호:"))
c[4]=int(input("다섯번째 자동차의 끝번호:"))
c[0]=int(input("첫번째 자동차의 끝번호:"))
c[1]=int(input("두번째 자동차의 끝번호:"))
c[2]=int(input("세번째 자동차의 끝번호:"))
c[3]=int(input("네번째 자동차의 끝번호:"))
c[4]=int(input("다섯번째 자동차의 끝번호:"))
c[0]=int(input("첫번째 자동차의 끝번호:"))
c[1]=int(input("두번째 자동차의 끝번호:"))
c[2]=int(input("세번째 자동차의 끝번호:"))
c[3]=int(input("네번째 자동차의 끝번호:"))
c[4]=int(input("다섯번째 자동차의 끝번호:"))
c[0]=int(input("첫번째 자동차의 끝번호:"))
c[1]=int(input("두번째 자동차의 끝번호:"))
c[2]=int(input("세번째 자동차의 끝번호:"))
c[3]=int(input("네번째 자동차의 끝번호:"))
c[4]=int(input("다섯번째 자동차의 끝번호:"))
c[0]=int(input("첫번째 자동차의 끝번호:"))
c[1]=int(input("두번째 자동차의 끝번호:"))
c[2]=int(input("세번째 자동차의 끝번호:"))
c[3]=int(input("네번째 자동차의 끝번호:"))
c[4]=int(input("다섯번째 자동차의 끝번호:"))
c[0]=int(input("첫번째 자동차의 끝번호:"))
c[1]=int(input("두번째 자동차의 끝번호:"))
c[2]=int(input("세번째 자동차의 끝번호:"))
c[3]=int(input("네번째 자동차의 끝번호:"))
c[4]=int(input("다섯번째 자동차의 끝번호:"))
c[0]=int(input("첫번째 자동차의 끝번호:"))
c[1]=int(input("두번째 자동차의 끝번호:"))
c[2]=int(input("세번째 자동차의 끝번호:"))
c[3]=int(input("네번째 자동차의 끝번호:"))
c[4]=int(input("다섯번째 자동차의 끝번호:"))
c[0]=int(input("첫번째 자동차의 끝번호:"))
c[1]=int(input("두번째 자동차의 끝번호:"))
c[2]=int(input("세번째 자동차의 끝번호:"))
c[3]=int(input("네번째 자동차의 끝번호:"))
c[4]=int(input("다섯번째 자동차의 끝번호:"))

co=0

for x in range(5):
    if d ==c[x]:
        co=co+1

print("위반한 차의 수:",co)
        
